/**
 * GitHub Action entry point for github-mobile-reader.
 *
 * Runs inside the Actions runner:
 *   1. Fetches the PR diff via `git diff`
 *   2. Generates a Reader Markdown document for each changed file
 *   3. Writes docs/reader/pr-<number>.md  (committed to the repo)
 *   4. Posts a summary comment on the PR via the GitHub REST API
 */

import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';
import { generateReaderMarkdown } from './parser';
import { summarizeWithGemini } from './gemini';

// ── Helpers ──────────────────────────────────────────────────────────────────

function env(name: string, fallback?: string): string {
  const val = process.env[name] ?? fallback;
  if (val === undefined) {
    throw new Error(`Required environment variable "${name}" is not set.`);
  }
  return val;
}

function run(cmd: string, cwd?: string): string {
  return execSync(cmd, {
    cwd: cwd ?? process.cwd(),
    encoding: 'utf8',
    stdio: ['pipe', 'pipe', 'pipe'],
  }).trim();
}

// ── Per-file diff extraction ──────────────────────────────────────────────────

interface FileDiff {
  filename: string;
  diff: string;
}

/**
 * Returns the raw diff split by file.
 * Uses `git diff origin/<base>...HEAD` so it covers all PR commits.
 */
function getFileDiffs(baseBranch: string): FileDiff[] {
  let rawDiff: string;
  try {
    rawDiff = run(`git diff origin/${baseBranch}...HEAD`);
  } catch {
    // Fallback: unstaged + staged changes
    rawDiff = run('git diff HEAD');
  }

  if (!rawDiff) return [];

  const fileDiffs: FileDiff[] = [];
  // Split on diff --git boundaries
  const chunks = rawDiff.split(/(?=^diff --git )/m).filter(Boolean);

  for (const chunk of chunks) {
    const fileMatch = chunk.match(/^diff --git a\/(.+?) b\//m);
    if (!fileMatch) continue;
    const filename = fileMatch[1];

    // Only process JS / TS files for now
    if (!/\.(js|jsx|ts|tsx|mjs|cjs)$/.test(filename)) continue;

    fileDiffs.push({ filename, diff: chunk });
  }

  return fileDiffs;
}

// ── Markdown output ───────────────────────────────────────────────────────────

async function writeMarkdown(
  outputDir: string,
  prNumber: string,
  fileDiffs: FileDiff[],
  meta: { repo: string; commit: string },
  geminiKey?: string,
): Promise<string> {
  const parts: string[] = [
    `# 📖 PR #${prNumber} — Mobile Reader View\n`,
    `> Repository: ${meta.repo}  `,
    `> Commit: \`${meta.commit}\`  `,
    `> Generated by **github-mobile-reader**\n`,
    '---\n',
  ];

  for (const { filename, diff } of fileDiffs) {
    const section = generateReaderMarkdown(diff, {
      pr: prNumber,
      commit: meta.commit,
      file: filename,
      repo: meta.repo,
    });

    parts.push(`## 📄 \`${filename}\`\n`);

    // AI summary (opt-in — only when GEMINI_API_KEY is set)
    if (geminiKey) {
      const summary = await summarizeWithGemini(filename, diff, geminiKey);
      if (summary) {
        const lines = summary.split('\n').filter(l => l.trim());
        const quoted = lines.map((l, i) => i === 0 ? `> 💡 ${l}` : `> ${l}`).join('\n');
        parts.push(quoted + '\n');
      }
    }

    parts.push(section);
    parts.push('\n---\n');
  }

  if (parts.length === 5) {
    // Only the header, no JS/TS changes
    parts.push('_No JavaScript / TypeScript changes detected in this PR._\n');
  }

  const outPath = path.join(outputDir, `pr-${prNumber}.md`);
  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(outPath, parts.join('\n'), 'utf8');

  console.log(`[github-mobile-reader] Written → ${outPath}`);
  return outPath;
}

// ── PR comment ───────────────────────────────────────────────────────────────

async function postComment(
  token: string,
  repo: string,
  prNumber: string,
  body: string
): Promise<void> {
  const [owner, repoName] = repo.split('/');
  const url = `https://api.github.com/repos/${owner}/${repoName}/issues/${prNumber}/comments`;

  const resp = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `token ${token}`,
      'Content-Type': 'application/json',
      Accept: 'application/vnd.github+json',
    },
    body: JSON.stringify({ body }),
  });

  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`GitHub API error ${resp.status}: ${text}`);
  }

  console.log('[github-mobile-reader] PR comment posted.');
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const token      = env('GITHUB_TOKEN');
  const repo       = env('GITHUB_REPOSITORY');           // owner/repo
  const prNumber   = env('PR_NUMBER');
  const baseBranch = env('BASE_BRANCH', 'main');
  const outputDir  = env('OUTPUT_DIR', 'docs/reader');
  const geminiKey  = process.env.GEMINI_API_KEY;         // optional
  const commit     = run('git rev-parse --short HEAD');

  console.log(`[github-mobile-reader] Processing PR #${prNumber} (${repo})`);
  if (geminiKey) console.log('[github-mobile-reader] Gemini AI summaries enabled');

  const fileDiffs = getFileDiffs(baseBranch);
  console.log(`[github-mobile-reader] Found ${fileDiffs.length} JS/TS file(s) with changes`);

  const outPath = await writeMarkdown(outputDir, prNumber, fileDiffs, { repo, commit }, geminiKey);

  // Build a short summary for the PR comment
  const fileList = fileDiffs.map(f => `- \`${f.filename}\``).join('\n') || '- (none)';
  const commentBody = [
    '## 📖 Mobile Reader View Generated',
    '',
    `A mobile-friendly summary has been written to \`${outPath}\`.`,
    '',
    '**Changed files processed:**',
    fileList,
    '',
    `> Powered by [github-mobile-reader](https://www.npmjs.com/package/github-mobile-reader)`,
  ].join('\n');

  await postComment(token, repo, prNumber, commentBody);
}

main().catch(err => {
  console.error('[github-mobile-reader] Fatal:', err.message);
  process.exit(1);
});
